//! Compile the runtime shim once, and enumerate the test corpus.
//!
//! Building the shim here rather than on demand means there is exactly one `shim.o` per build, and
//! the driver, the golden-program tests, and the differential harness all link that same object —
//! which is what makes a comparison against `clang` apples to apples.
//!
//! `-Werror` is deliberate: the shim is small enough that a warning in it is a defect, and a build
//! failure is a louder way to say so than a line of output nobody reads.
//!
//! The corpus listing exists because each program in `tests/programs/` is its own `#[test]`, so a
//! failure names the program that broke rather than collapsing the suite into one red line — and
//! Rust needs those test functions at compile time. Generating the list from the directory rather
//! than writing it out by hand removes the only way a program can be added and silently never run.

// The compiler's no-panic rule is about user input reaching a pass, which has a diagnostic channel
// to report through. A build script has none: failing loudly is the only way it can report at all.
#![allow(clippy::expect_used, clippy::panic)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Where the shim's source lives, relative to the crate root.
const SHIM_SOURCE: &str = "runtime/shim.c";

/// Where the subset-C test corpus lives, relative to the crate root.
const CORPUS: &str = "tests/programs";

/// Compile the shim, export its path, and write the corpus listing the test harnesses expand.
fn main() {
    println!("cargo::rerun-if-changed={SHIM_SOURCE}");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed={CORPUS}");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("cargo always sets OUT_DIR"));
    write_corpus_listing(&out_dir);

    let object = out_dir.join("shim.o");

    let output = Command::new("clang")
        .args(["-std=c99", "-O0", "-Wall", "-Wextra", "-Werror", "-c"])
        .arg(SHIM_SOURCE)
        .arg("-o")
        .arg(&object)
        .output()
        .unwrap_or_else(|error| {
            panic!(
                "could not run clang to build {SHIM_SOURCE}: {error}\n\
                 Xcode Command Line Tools are required; run `xcode-select --install`."
            )
        });

    assert!(
        output.status.success(),
        "clang failed to build {SHIM_SOURCE}:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );

    println!("cargo::rustc-env=RUSTYCC_SHIM_OBJECT={}", object.display());
}

/// Write `$OUT_DIR/corpus.rs`, a macro naming every program in the corpus.
///
/// The file defines one macro, `corpus!`, which takes the name of a second macro and calls it with
/// every program name. A harness supplies its own per-program macro and gets a `#[test]` for each
/// program, so the differential suite and the golden-program suite read the same list without
/// either one restating it.
fn write_corpus_listing(out_dir: &Path) {
    let mut names: Vec<String> = fs::read_dir(CORPUS)
        .unwrap_or_else(|error| panic!("could not read {CORPUS}: {error}"))
        .filter_map(|entry| {
            let path = entry.expect("a corpus entry should be readable").path();
            let is_program = path.extension().is_some_and(|extension| extension == "c");

            is_program
                .then(|| {
                    path.file_stem()
                        .and_then(|stem| stem.to_str())
                        .map(str::to_owned)
                })
                .flatten()
        })
        .collect();
    // Sorted so the generated file — and so the order tests are declared in — depends on the corpus
    // rather than on whatever order the filesystem happened to hand back.
    names.sort();

    assert!(!names.is_empty(), "{CORPUS} holds no programs");

    let listing = format!(
        "/// Calls `$per_program` with the name of every program in `{CORPUS}`.\n\
         ///\n\
         /// Generated by `build.rs` from the directory itself; do not edit.\n\
         macro_rules! corpus {{\n    ($per_program:ident) => {{\n        $per_program! {{\n{}\n        }}\n    }};\n}}\n",
        names
            .iter()
            .map(|name| format!("            {name},"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    fs::write(out_dir.join("corpus.rs"), listing).expect("could not write the corpus listing");
}
