//! The golden-program corpus: every program compiled by `rustycc`, run, and checked against the
//! answer written in its own header.
//!
//! The header's exit code and stdout were recorded from `clang -O0 -std=c99`, not from this
//! compiler, so they are an independent answer rather than a note of what `rustycc` happened to do
//! on the day. `tests/differential.rs` puts the same question to `clang` live; this tier is the
//! written-down version of the same answer, and it is the faster of the two to read when something
//! breaks — a header says what the program is supposed to print, which a live comparison never has
//! to state out loud.
//!
//! One `#[test]` per program, so a failure names the program that broke rather than collapsing the
//! corpus into one red line.

// clippy.toml exempts test code from the panic-adjacent lints, but only inside `#[test]` bodies;
// the helpers below are test scaffolding too, and a corpus file that cannot be read is a broken
// checkout rather than something to report a diagnostic about.
#![allow(clippy::expect_used, clippy::panic)]

mod harness;

use std::fs;
use std::path::Path;

use harness::Exit;

/// Where the corpus lives, relative to the crate root Cargo runs tests from.
const CORPUS: &str = "tests/programs";

// The list of programs, generated by `build.rs` from the directory itself, so a program cannot be
// added to the corpus and silently never run.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// Declares one `#[test]` per corpus program.
macro_rules! golden_programs {
    ($($name:ident),* $(,)?) => {
        $(
            #[doc = concat!("`", stringify!($name), ".c` does what its own header says it does.")]
            #[test]
            fn $name() {
                run_golden(stringify!($name));
            }
        )*
    };
}

corpus!(golden_programs);

/// What a program's header says it should do.
struct Expected {
    /// The exit status.
    code: i32,
    /// Everything it should write to stdout.
    stdout: String,
}

/// Reads the `expect-` header of the program at `path`.
///
/// `\n` and `\t` are written as escapes so the whole expectation fits on one comment line; they are
/// decoded here rather than compared as text, so a program emitting a literal backslash-n is told
/// apart from one emitting a newline.
fn expectations(path: &Path, source: &str) -> Expected {
    let field = |key: &str| {
        let prefix = format!("// expect-{key}: ");

        source
            .lines()
            .find_map(|line| line.strip_prefix(&prefix))
            .unwrap_or_else(|| panic!("{} has no `// expect-{key}:` line", path.display()))
            .to_owned()
    };

    let code = field("exit")
        .parse()
        .unwrap_or_else(|_| panic!("{}: the expected exit code is not a number", path.display()));

    Expected {
        code,
        stdout: decode(&field("stdout")),
    }
}

/// Turns the escapes a header uses back into the bytes they stand for.
fn decode(encoded: &str) -> String {
    let mut decoded = String::new();
    let mut characters = encoded.chars();

    while let Some(character) = characters.next() {
        if character != '\\' {
            decoded.push(character);

            continue;
        }

        match characters.next() {
            Some('n') => decoded.push('\n'),
            Some('t') => decoded.push('\t'),
            Some('\\') => decoded.push('\\'),
            Some(other) => {
                decoded.push('\\');
                decoded.push(other);
            }
            None => decoded.push('\\'),
        }
    }

    decoded
}

/// Compiles `name` from the corpus with `rustycc`, runs it, and checks it against its header.
fn run_golden(name: &str) {
    let path = Path::new(CORPUS).join(format!("{name}.c"));
    let source = fs::read(&path).expect("a corpus program should be readable");
    let text = String::from_utf8_lossy(&source).into_owned();
    let expected = expectations(&path, &text);

    let directory = harness::scratch("golden", name);
    let built = harness::build_with_rustycc(&path, &source, &directory)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    let run = harness::execute(&built.binary, &directory, harness::timeout());
    let stdout = String::from_utf8_lossy(&run.stdout).into_owned();

    assert_eq!(
        stdout,
        expected.stdout,
        "{}: stdout does not match\n  expected: {:?}\n  actual:   {:?}\nartifacts kept in {}",
        path.display(),
        expected.stdout,
        stdout,
        directory.display()
    );
    assert_eq!(
        run.exit,
        Exit::Code(expected.code),
        "{}: the program ended differently; artifacts kept in {}",
        path.display(),
        directory.display()
    );
}
