//! The acceptance suite: every corpus program compiled by `rustycc` and by `clang`, both run, both
//! compared.
//!
//! This is the tier that replaces recorded expectations with a live oracle. A golden test asserts
//! that a program still does what it did when someone wrote the answer down; this asserts that it
//! does what `clang -O0` says it should, which is an answer nobody on this project wrote. The
//! project is functionally complete when this run is green over the whole corpus, and not before.
//!
//! A failing test here is a compiler bug until proven otherwise. Adjusting the program or moving it
//! out of the corpus to get back to green throws away the only evidence the suite exists to
//! produce.

// clippy.toml exempts test code from the panic-adjacent lints, but only inside `#[test]` bodies;
// the helpers below are test scaffolding too, and a corpus file that cannot be read is a broken
// checkout rather than something to report a diagnostic about.
#![allow(clippy::expect_used, clippy::panic)]

mod harness;

use std::fs;
use std::path::Path;
use std::process::Command;

use harness::Verdict;

/// Where the corpus lives, relative to the crate root Cargo runs tests from.
const CORPUS: &str = "tests/programs";

// The list of programs, generated by `build.rs` from the directory itself, so a program cannot be
// added to the corpus and silently never run.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// Declares one `#[test]` per corpus program.
///
/// One test per program rather than one loop over all of them, so a failure names the program that
/// broke and the rest still report, instead of the whole corpus collapsing into a single red line
/// at the first disagreement.
macro_rules! differential_tests {
    ($($name:ident),* $(,)?) => {
        $(
            #[doc = concat!("`", stringify!($name), ".c` behaves identically under both compilers.")]
            #[test]
            fn $name() {
                compare_against_clang(stringify!($name));
            }
        )*
    };
}

corpus!(differential_tests);

/// Builds one corpus program both ways, runs both, and fails with a readable report on any
/// disagreement.
fn compare_against_clang(name: &str) {
    let path = Path::new(CORPUS).join(format!("{name}.c"));
    let directory = harness::scratch("differential", name);
    let verdict = harness::differential(&path, &directory);

    if let Some(report) = harness::report(&path, &directory, &verdict) {
        panic!("{report}");
    }

    // Agreement is only evidence if there was something to agree about. A program that prints
    // nothing passes this suite no matter how badly the compiler is broken, so the corpus is held
    // to producing output rather than trusted to.
    let Verdict::Agreed(run) = verdict else {
        unreachable!("a failing verdict was reported above")
    };
    assert!(
        !run.stdout.is_empty(),
        "{}: the program printed nothing, so comparing it proves nothing",
        path.display()
    );
}

/// Every warning `clang` has about a corpus program is one the program says it is provoking.
///
/// The corpus exists to test the corners of the grammar, and some of those corners — `a || b && c`
/// without parentheses, an `else` with two `if`s to choose from — are exactly what `-Wall` is for.
/// Silencing them by rewriting the program would delete the test; ignoring them would let a real
/// warning about a program that is accidentally relying on something arrive unnoticed. So a program
/// declares the warnings it means to provoke in a `// clang-warns:` header, and the declared set
/// has to match what `clang` actually says, exactly. A warning that appears without being declared
/// fails, and so does one declared after it stops happening.
#[test]
fn every_clang_warning_about_the_corpus_is_declared() {
    let directory = harness::scratch("differential", "warnings");
    let mut complaints = Vec::new();

    for path in programs() {
        let source = fs::read_to_string(&path).expect("a corpus program should be readable");
        let compiled = Command::new("clang")
            .args(["-std=c99", "-O0", "-Wall", "-Wextra", "-c"])
            .arg(&path)
            .arg("-o")
            .arg(directory.join("check.o"))
            .output()
            .expect("could not run clang; run xcode-select --install");
        let said = String::from_utf8_lossy(&compiled.stderr).into_owned();

        if !compiled.status.success() {
            complaints.push(format!("{}: clang rejected it:\n{said}", path.display()));

            continue;
        }

        let reported = warning_flags(&said);
        let declared = declared_warnings(&source);

        if reported != declared {
            complaints.push(format!(
                "{}: declares {declared:?} but clang reported {reported:?}\n{said}",
                path.display()
            ));
        }
    }

    assert!(
        complaints.is_empty(),
        "the corpus and clang disagree about warnings:\n{}",
        complaints.join("\n")
    );
}

/// The warning flags named in `clang`'s output, as the `-Wname` each message ends with.
fn warning_flags(said: &str) -> Vec<String> {
    let mut flags: Vec<String> = said
        .match_indices("[-W")
        .filter_map(|(start, _)| {
            let rest = said.get(start + 1..)?;
            let end = rest.find(']')?;

            rest.get(..end).map(str::to_owned)
        })
        .collect();
    flags.sort();
    flags.dedup();

    flags
}

/// The warning flags a program's `// clang-warns:` header says it provokes.
fn declared_warnings(source: &str) -> Vec<String> {
    let mut flags: Vec<String> = source
        .lines()
        .find_map(|line| line.strip_prefix("// clang-warns: "))
        .unwrap_or_default()
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    flags.sort();
    flags.dedup();

    flags
}

/// Every `.s` this compiler emits for the corpus assembles on its own with nothing to report.
///
/// The comparison tests link and run, which succeed despite a warning. A directive the assembler
/// grumbles about is one this compiler should not be emitting even when the program works.
///
/// Its artifacts go under a directory of their own rather than beside the comparison's. Cargo runs
/// these tests in parallel, and this one walks every program, so sharing a directory with the
/// per-program test for that same program would have the two writing one `.s` at once.
#[test]
fn every_program_assembles_without_warnings() {
    let mut complaints = Vec::new();

    for path in programs() {
        let name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_default()
            .to_owned();
        let directory = harness::scratch("assembles", &name);
        let source = fs::read(&path).expect("a corpus program should be readable");
        let built = harness::build_with_rustycc(&path, &source, &directory)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        let assembly = built
            .assembly
            .unwrap_or_else(|| panic!("{}: no assembly was retained", path.display()));

        let assembled = Command::new("clang")
            .args(["-c", "-Werror"])
            .arg(&assembly)
            .arg("-o")
            .arg(directory.join("warnings.o"))
            .output()
            .expect("could not run clang");

        if !assembled.status.success() || !assembled.stderr.is_empty() {
            complaints.push(format!(
                "{name}:\n{}",
                String::from_utf8_lossy(&assembled.stderr)
            ));
        }
    }

    assert!(
        complaints.is_empty(),
        "the assembler had something to say:\n{}",
        complaints.join("\n")
    );
}

/// The corpus is large enough to be the acceptance suite the plan asks for.
///
/// A number rather than a vague "enough": the plan's target is sixty programs, and a suite that
/// quietly shrinks below it has stopped being the thing this phase signed off on.
#[test]
fn the_corpus_meets_its_size_target() {
    let count = programs().len();

    assert!(
        count >= 60,
        "the corpus has {count} programs; the acceptance suite needs at least 60"
    );
}

/// Every `.c` file directly under `tests/programs/`, sorted.
///
/// The `invalid/` subdirectory is deliberately not included: those programs are the ones that must
/// be rejected, and they are held to that by `tests/invalid_programs.rs`.
fn programs() -> Vec<std::path::PathBuf> {
    let mut found: Vec<_> = fs::read_dir(CORPUS)
        .expect("the corpus directory should exist")
        .filter_map(|entry| {
            let path = entry.expect("a corpus entry should be readable").path();
            let is_program = path.extension().is_some_and(|extension| extension == "c");

            is_program.then_some(path)
        })
        .collect();
    found.sort();

    found
}
