#!/usr/bin/env bash
#
# Capture evidence for the system-level test plan: what the `rustycc` executable does at its CLI
# boundary — stdout, stderr, exit status, and the files it writes. Companion to
# scripts/test-evidence.sh, which covers the unit tier from inside the crate.
#
# Writes docs/reports/system_tests/evidence_system.md. Section IDs match the test case IDs in the
# system test plan. Every command is run from the repository root with relative paths, so the
# transcript reads the same way a grader would type it.
#
# Usage: scripts/system-test-evidence.sh

set -u

cd "$(dirname "$0")/.."

for directory in "$HOME/.cargo/bin" "$HOME/.local/bin" /opt/homebrew/bin; do
	case ":$PATH:" in
	*":$directory:"*) ;;
	*) [ -d "$directory" ] && PATH="$PATH:$directory" ;;
	esac
done
export PATH

out="docs/reports/system_tests/evidence_system.md"
work="target/system-test-work"
bin="target/debug/rustycc"
fence='```'

mkdir -p "$(dirname "$out")"
rm -rf "$work"
mkdir -p "$work"

cargo build || exit 1

{
	printf '<!-- Generated by scripts/system-test-evidence.sh on %s -->\n\n' \
		"$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
	printf '# System Test Evidence\n\n'
	printf 'Commit: `%s`\n\n' "$(git rev-parse HEAD)"
	printf 'Every command below was run from the repository root. `%s` is the freshly built\n' "$bin"
	printf 'compiler; `%s/` is a scratch directory this script creates and removes.\n' "$work"
} >"$out"

section() { printf '\n\n## %s\n' "$1" >>"$out"; }

runsh() {
	local id="$1" cmd="$2" status
	{
		printf '\n### %s\n\n' "$id"
		printf '%sconsole\n$ %s\n' "$fence" "$cmd"
	} >>"$out"
	bash -c "$cmd" >>"$out" 2>&1
	status=$?
	printf '[exit %d]\n%s\n' "$status" "$fence" >>"$out"
}

# ------------------------------------------------------------------ fixtures

cat >"$work/demo.c" <<'EOF_DEMO'
void print_int(int n);
void print_char(char c);
void print_string(char s[]);

int square(int n) { return n * n; }

int main(void) {
    print_string("squares: ");
    for (int i = 1; i <= 5; i = i + 1) {
        print_int(square(i));
        print_char(' ');
    }
    print_char('\n');
    return 0;
}
EOF_DEMO

cat >"$work/exit300.c" <<'EOF_EXIT'
int main(void) { return 300; }
EOF_EXIT

cat >"$work/errors.c" <<'EOF_ERRORS'
int main(void) {
    int total;
    int total;
    return missing;
}
EOF_ERRORS

printf 'struct P { int x; };\nint main(void) { return 0; }\n'     >"$work/x_struct.c"
printf 'int main(void) { int x = 1; switch (x) { } return 0; }\n' >"$work/x_switch.c"
printf 'int main(void) { return 1 ? 2 : 3; }\n'                   >"$work/x_ternary.c"
printf 'int main(void) { do { } while (0); return 0; }\n'         >"$work/x_dowhile.c"
printf 'int main(void) { int x = 1; x += 2; return x; }\n'        >"$work/x_compound.c"
printf 'int main(void) { return 1 & 2; }\n'                       >"$work/x_bitwise.c"
printf 'int main(void) { return sizeof(int); }\n'                 >"$work/x_sizeof.c"
printf 'int main(void) { int *p; return 0; }\n'                   >"$work/x_pointer.c"
printf '#define N 4\nint main(void) { return N; }\n'              >"$work/x_preproc.c"

head -c 4096 /dev/urandom >"$work/garbage.c"

# ------------------------------------------------------------------ versions

section "Environment"
runsh "ENV-1" "sw_vers"
runsh "ENV-2" "uname -m"
runsh "ENV-3" "xcode-select -p && xcodebuild -version"
runsh "ENV-4" "clang --version"
runsh "ENV-5" "rustc --version && cargo --version && rustup show active-toolchain"
runsh "ENV-6" "git --version"
runsh "ENV-7" "cargo tree --depth 1 -e normal,build,dev"
runsh "ENV-8" "cargo fuzz --version; cargo insta --version; uv --version"
runsh "ENV-9" "$bin --version"

# ------------------------------------------------------- UC-01 compile and run

section "UC-01  Compile and run a program"
runsh "ST-01.1" "$bin $work/demo.c -o $work/demo && $work/demo"
runsh "ST-01.2" "cd $work && ../../$bin demo.c && ls -l demo && ./demo"
runsh "ST-01.3" "$bin $work/exit300.c -o $work/exit300 && $work/exit300; echo \"exit status: \$?\""
runsh "ST-01.4" "file $work/demo"

# --------------------------------------------------- UC-02 reject and report

section "UC-02  Reject an invalid program"
runsh "ST-02.1" "$bin --check $work/errors.c"
runsh "ST-02.2" "$bin --check $work/errors.c 2>&1 >/dev/null | grep -c 'error:'"
runsh "ST-02.3" "$bin --check $work/errors.c 2>&1 >/dev/null | grep -n 'note:'"
runsh "ST-02.4" "$bin --check $work/errors.c >$work/out.txt 2>$work/err.txt; echo \"stdout bytes: \$(wc -c <$work/out.txt)\"; tail -1 $work/err.txt"

# -------------------------------------------------------- UC-03 subset bounds

section "UC-03  Constructs outside the subset, reported by name"
for construct in struct switch ternary dowhile compound bitwise sizeof pointer preproc; do
	runsh "ST-03.$construct" "$bin --check $work/x_$construct.c"
done
runsh "ST-03.deviations" "grep -c '^| \[' tests/programs/invalid/COVERAGE.md; grep -c 'deviation' tests/programs/invalid/COVERAGE.md"

# ----------------------------------------------------------- UC-04 CLI misuse

section "UC-04  Command-line misuse"
runsh "ST-04.1" "$bin"
runsh "ST-04.2" "$bin $work/nope.c"
runsh "ST-04.3" "$bin $work/demo.c --dump-tokens --check"
runsh "ST-04.4" "$bin --help"

# ----------------------------------------------------- UC-05 stage inspection

section "UC-05  Stage inspection"
runsh "ST-05.1" "$bin tests/programs/arithmetic.c --dump-tokens | head -20"
runsh "ST-05.2" "$bin tests/programs/arithmetic.c --dump-ast | head -20"
runsh "ST-05.3" "$bin tests/programs/arithmetic.c --dump-annotations | head -20"
runsh "ST-05.4" "$bin --check tests/programs/arithmetic.c; echo \"exit: \$?\""
runsh "ST-05.5" "cd $work && ../../$bin demo.c --dump-tokens >/dev/null; ls"

# --------------------------------------------------------- UC-06 artifacts

section "UC-06  Intermediate artifacts"
runsh "ST-06.1" "$bin $work/demo.c -S -o $work/demo.s && head -20 $work/demo.s"
runsh "ST-06.2" "clang -c $work/demo.s -o $work/from_asm.o && file $work/from_asm.o"
runsh "ST-06.3" "$bin $work/demo.c -c -o $work/demo.o && file $work/demo.o"
runsh "ST-06.4" "$bin $work/demo.c -o $work/demo_kt --keep-temps"
runsh "ST-06.5" "$bin $work/demo.c -o $work/demo_emit --emit-asm-to $work/side.s && ls -l $work/demo_emit $work/side.s"

# -------------------------------------------------------- UC-07 equivalence

section "UC-07  Behavioral equivalence with clang"
runsh "ST-07.1" "shim=\$(find target/debug/build -name shim.o | head -1); clang -O0 -std=c99 tests/programs/sorting.c \"\$shim\" -o $work/oracle && $bin tests/programs/sorting.c -o $work/ours && diff <($work/oracle; echo \"exit \$?\") <($work/ours; echo \"exit \$?\") && echo identical"
runsh "ST-07.2" "cargo test --test differential 2>&1 | tail -12"
runsh "ST-07.3" "cargo test --test codegen_exec 2>&1 | tail -6"
runsh "ST-07.4" "cargo test --test invalid_programs 2>&1 | tail -6"
runsh "ST-07.5" "RUSTYCC_GENERATED_PROGRAMS=200 RUSTYCC_GENERATED_SEED=987654321 cargo test --test generated 2>&1 | tail -6"

# --------------------------------------------------------- UC-08 robustness

section "UC-08  Robustness"
runsh "ST-08.1" "$bin $work/garbage.c --dump-tokens >$work/garbage.out 2>&1; echo \"exit: \$?\"; echo \"diagnostic lines: \$(wc -l <$work/garbage.out)\""
runsh "ST-08.2" "$bin --check tests/adversarial/deep_parens.c 2>&1 | head -4"
runsh "ST-08.3" "$bin --check tests/adversarial/deep_unclosed_parens.c 2>&1 | head -4"
runsh "ST-08.4" "for f in tests/adversarial/*.c; do printf '%-48s ' \"\$f\"; $bin --check \"\$f\" >/dev/null 2>&1; echo \"exit \$?\"; done"
runsh "ST-08.5" "cargo test --test frontend_no_panic 2>&1 | tail -6"
runsh "ST-08.6" "cargo test --test harness_self_tests 2>&1 | tail -6"

# ------------------------------------------------------- UC-09 shim and CLI

section "UC-09  Runtime shim and driver"
runsh "ST-09.1" "cargo test --test runtime_shim 2>&1 | tail -8"
runsh "ST-09.2" "cargo test --test cli 2>&1 | tail -8"

# ---------------------------------------------------------- UC-10 the gate

section "UC-10  Full local gate"
runsh "ST-10.1" "cargo fmt --check; echo \"exit: \$?\""
runsh "ST-10.2" "cargo clippy --all-targets -- -D warnings 2>&1 | tail -4"
runsh "ST-10.3" "cargo test 2>&1 | grep -E '^(test result|running)'"
runsh "ST-10.4" "./scripts/build-docs.sh >/dev/null 2>&1; echo \"docs build exit: \$?\""

rm -rf "$work"
echo "wrote $out"
